### ISSUE TITLE
Brickhouse to_json UDF does not support Hive's Decimal type

### ISSUE THREAD

**Issue by mp1118** [klout/brickhouse#171]
Attempting to convert any complex type that contains a Hive Decimal field results in:
```
org.apache.hive.service.cli.HiveSQLException: Error while compiling statement: FAILED: SemanticException [Error 10014]: Line 113:28 Wrong arguments 'field_name': Don't know how to handle object inspector org.apache.hadoop.hive.serde2.objectinspector.primitive.WritableHiveDecimalObjectInspector
```

Since Brickhouse is built against Hive 0.1.0 this isn't a straightforward change.  The library would need to be updated to at least 0.13.

Are there any plans to upgrade this library?

**Comment by jeromebanks** [comment]
Michael,     Feel free to fork and build your own release.  People have been maintaining their own internal releases, but no current plans for another public build.

    On Friday, April 3, 2020, 01:37:31 PM PDT, Michael Polansky <notifications@github.com> wrote:  
 
 


Attempting to convert any complex type that contains a Hive Decimal field results in:
org.apache.hive.service.cli.HiveSQLException: Error while compiling statement: FAILED: SemanticException [Error 10014]: Line 113:28 Wrong arguments 'field_name': Don't know how to handle object inspector org.apache.hadoop.hive.serde2.objectinspector.primitive.WritableHiveDecimalObjectInspector

Since Brickhouse is built against Hive 0.1.0 this isn't a straightforward change. The library would need to be updated to at least 0.13.

Are there any plans to upgrade this library?
